[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_v2_example = "B5SqvrzM1UTWxpMi5GqwfAj6L6fjEdD5uANdyBH11pvE"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
